# Generated by Django 5.2.3 on 2025-06-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('VIRTUAL_ACCOUNT', 'Virtual Account'), ('VA_BCA', 'BCA Virtual Account'), ('VA_BNI', 'BNI Virtual Account'), ('VA_BRI', 'BRI Virtual Account'), ('VA_MANDIRI', 'Mandiri Virtual Account'), ('VA_PERMATA', 'Permata Virtual Account'), ('VA_BSI', 'BSI Virtual Account'), ('CREDIT_CARD', 'Credit/Debit Card'), ('QRIS', 'QR Code (QRIS)'), ('QR_CODE', 'QR Code')], max_length=20),
        ),
    ]
