# Generated by Django 5.2.3 on 2025-06-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction_payment_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='xendit_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='xendit_qr_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
